package wamedia_test

import (
	"bytes"
	"encoding/base64"
	"encoding/json"
	"flag"
	"os"
	"path/filepath"
	"testing"

	"whatserver2/internal/crypto/wamedia"
)

// Attachments are decrypted in the browser, so this scheme also gets a second
// implementation in another language. The parts easy to get wrong are not the
// AES: they are that the HMAC covers the IV as well as the ciphertext, that it
// is truncated to ten bytes, that several media types deliberately share one
// HKDF label, and that the expansion is 112 bytes even though only 80 are used.
// Every one of those is silent when wrong — a MAC mismatch on real media, and
// nothing to point at.
//
// Regenerate deliberately:
//
//	go test ./internal/crypto/wamedia -run Vectors -update
var update = flag.Bool("update", false, "regenerate testdata/vectors.json")

const vectorsPath = "testdata/vectors.json"

type vectors struct {
	Note    string   `json:"note"`
	Vectors []vector `json:"vectors"`
}

type vector struct {
	Type      string `json:"type"`
	MediaKey  string `json:"media_key"`
	Plaintext string `json:"plaintext"`
	// Enc is exactly what the CDN serves: ciphertext followed by ten MAC bytes.
	Enc string `json:"enc"`
	// Derived is the HKDF expansion, so an implementation that fails can see
	// which of the three values went wrong instead of only that the MAC did.
	IV        string `json:"iv"`
	CipherKey string `json:"cipher_key"`
	MACKey    string `json:"mac_key"`
	Note      string `json:"note,omitempty"`
}

func b64(b []byte) string { return base64.StdEncoding.EncodeToString(b) }

func unb64(t *testing.T, s string) []byte {
	t.Helper()
	b, err := base64.StdEncoding.DecodeString(s)
	if err != nil {
		t.Fatalf("decoding fixture bytes: %v", err)
	}
	return b
}

func TestVectors(t *testing.T) {
	if *update {
		writeVectors(t)
	}

	raw, err := os.ReadFile(vectorsPath)
	if err != nil {
		t.Fatalf("reading the vectors: %v (run with -update to create them)", err)
	}
	var v vectors
	if err := json.Unmarshal(raw, &v); err != nil {
		t.Fatalf("parsing the vectors: %v", err)
	}
	if len(v.Vectors) == 0 {
		t.Fatal("the vectors file is empty")
	}

	for _, want := range v.Vectors {
		t.Run(want.Type, func(t *testing.T) {
			key := unb64(t, want.MediaKey)

			k, err := wamedia.DeriveKeys(key, wamedia.Type(want.Type))
			if err != nil {
				t.Fatalf("deriving keys: %v", err)
			}
			if !bytes.Equal(k.IV, unb64(t, want.IV)) {
				t.Error("the derived IV does not match the fixture")
			}
			if !bytes.Equal(k.Cipher, unb64(t, want.CipherKey)) {
				t.Error("the derived cipher key does not match the fixture")
			}
			if !bytes.Equal(k.MAC, unb64(t, want.MACKey)) {
				t.Error("the derived MAC key does not match the fixture")
			}

			got, err := wamedia.Decrypt(unb64(t, want.Enc), key, wamedia.Type(want.Type))
			if err != nil {
				t.Fatalf("decrypting: %v", err)
			}
			if !bytes.Equal(got, unb64(t, want.Plaintext)) {
				t.Fatalf("decrypted to %d bytes, want %d", len(got), len(unb64(t, want.Plaintext)))
			}
		})
	}
}

func writeVectors(t *testing.T) {
	t.Helper()

	// Lengths chosen around the block boundary, because that is where padding
	// goes wrong: one byte short of a block, exactly a block (which must gain a
	// whole block of padding), and one over.
	cases := []struct {
		typ  wamedia.Type
		size int
		note string
	}{
		{wamedia.Image, 15, "one byte short of a block"},
		{wamedia.Image, 16, "exactly one block, so a full block of padding is added"},
		{wamedia.Image, 17, "one byte into a second block"},
		{wamedia.Sticker, 64, "shares the image HKDF label, deliberately"},
		{wamedia.Video, 4096, ""},
		{wamedia.PTV, 100, "rides on the video label"},
		{wamedia.Audio, 333, ""},
		{wamedia.PTT, 1000, "rides on the audio label"},
		{wamedia.Document, 8192, ""},
		{wamedia.Image, 0, "empty plaintext still produces a full block of padding"},
	}

	v := vectors{
		Note: "Generated by go test ./internal/crypto/wamedia -run Vectors -update. " +
			"enc is exactly what the WhatsApp CDN serves: ciphertext || hmac[:10].",
	}

	for i, c := range cases {
		key := make([]byte, wamedia.KeyLen)
		for j := range key {
			key[j] = byte((i+1)*31 + j*3)
		}
		plaintext := make([]byte, c.size)
		for j := range plaintext {
			plaintext[j] = byte(j % 251)
		}

		k, err := wamedia.DeriveKeys(key, c.typ)
		if err != nil {
			t.Fatal(err)
		}
		enc, err := wamedia.Encrypt(plaintext, key, c.typ)
		if err != nil {
			t.Fatal(err)
		}

		v.Vectors = append(v.Vectors, vector{
			Type: string(c.typ), MediaKey: b64(key),
			Plaintext: b64(plaintext), Enc: b64(enc),
			IV: b64(k.IV), CipherKey: b64(k.Cipher), MACKey: b64(k.MAC),
			Note: c.note,
		})
	}

	if err := os.MkdirAll(filepath.Dir(vectorsPath), 0o755); err != nil {
		t.Fatal(err)
	}
	out, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(vectorsPath, append(out, '\n'), 0o644); err != nil {
		t.Fatal(err)
	}
	t.Logf("wrote %s", vectorsPath)
}
