import { test } from 'node:test'
import assert from 'node:assert/strict'
import { auth } from '@modelcontextprotocol/client'
import { harness, authorize, authorizeURL, clientProvider, consent, exchange, pkce, refresh, register, rpc, session, secretsAbsent, REDIRECT_URI } from './harness.mjs'

const chatgpt = ['https://chatgpt.com/connector/oauth/abc123', 'https://chatgpt.com/connector_platform_oauth_redirect']

test('registration: allowlisted HTTPS redirects only, the auth method is assigned none, duplicates collapse, caps answer 429', async t => {
  const h = await harness(t, { env: { WAPPIE_MCP_REDIRECT_HOSTS: 'claude.ai,chatgpt.com,a.test,b.test' } })
  // Registrations are five a minute per address; the clock moves so the many below stay under it.
  const paced = (h, metadata) => { h.clock.advance(13_000); return register(h, metadata) }
  for (const bad of ['https://evil.claude.ai/cb', 'http://claude.ai/cb', 'https://claude.ai.attacker.com/cb', 'https://claude.ai:8443/cb', 'https://user@claude.ai/cb', 'https://claude.ai/cb#frag', 'ftp://claude.ai/cb', 'claude.ai/cb', '']) {
    const response = await paced(h, { redirect_uris: [bad] })
    assert.equal(response.status, 400, bad)
    assert.equal(response.json().error, 'invalid_redirect_uri')
  }
  assert.equal((await paced(h, { redirect_uris: [] })).json().error, 'invalid_redirect_uri')
  assert.equal((await paced(h, { redirect_uris: Array.from({ length: 6 }, (_, index) => `https://claude.ai/cb${index}`) })).json().error, 'invalid_redirect_uri')
  assert.equal((await paced(h, { redirect_uris: [REDIRECT_URI, chatgpt[0]] })).json().error, 'invalid_redirect_uri')
  assert.equal((await paced(h, { grant_types: ['client_credentials'] })).json().error, 'invalid_client_metadata')
  assert.equal((await paced(h, { response_types: ['token'] })).json().error, 'invalid_client_metadata')
  assert.equal((await paced(h, { client_name: 'x'.repeat(101) })).json().error, 'invalid_client_metadata')
  assert.equal((await paced(h, { client_name: 'bad' + String.fromCharCode(9) + 'name' })).json().error, 'invalid_client_metadata')
  assert.equal((await paced(h, { token_endpoint_auth_method: 7 })).json().error, 'invalid_client_metadata')
  assert.equal((await h.request('/mcp/register', { method: 'POST', headers: { 'content-type': 'application/json' }, body: '[' })).json().error, 'invalid_client_metadata')
  assert.equal((await h.request('/mcp/register', { method: 'POST', headers: { 'content-type': 'text/plain' }, body: '{}' })).status, 400)
  assert.equal((await h.request('/mcp/register')).status, 405)
  for (const method of ['client_secret_post', 'client_secret_basic', 'none', 'private_key_jwt']) {
    const response = await paced(h, { token_endpoint_auth_method: method, client_name: `Client ${method}` })
    assert.equal(response.status, 201)
    const body = response.json()
    assert.equal(body.token_endpoint_auth_method, 'none')
    assert.equal(body.client_secret, undefined)
    assert.equal(response.headers.get('cache-control'), 'no-store')
  }
  const gpt = await paced(h, { client_name: 'ChatGPT', redirect_uris: chatgpt })
  assert.equal(gpt.status, 201)
  assert.deepEqual(gpt.json().redirect_uris, chatgpt)
  const same = await paced(h, { client_name: 'ChatGPT', redirect_uris: [...chatgpt].reverse() })
  assert.equal(same.json().client_id, gpt.json().client_id, 'an identical registration returns the existing client')
  const minimal = await paced(h, { redirect_uris: [REDIRECT_URI], client_name: undefined, grant_types: undefined, response_types: undefined, token_endpoint_auth_method: undefined })
  assert.equal(minimal.status, 201)
  assert.deepEqual(minimal.json().grant_types, ['authorization_code'])
  const clients = h.reader.state.clients
  const ofHost = host => [...clients.values()].filter(client => client.redirect_host === host)
  const pin = () => { for (const client of clients.values()) client.authorized_at = h.clock.now() }
  for (let index = 0; ofHost('claude.ai').length < 200; index++) assert.equal((await paced(h, { client_name: `claude ${index}`, redirect_uris: [`https://claude.ai/cb/${index}`] })).status, 201)
  const oldest = ofHost('claude.ai').reduce((found, client) => (client.last_used_at < found.last_used_at ? client : found))
  const hostFull = await paced(h, { client_name: 'one more', redirect_uris: ['https://claude.ai/cb/overflow'] })
  assert.equal(hostFull.status, 201, 'at the host cap the client nobody consented to that was used longest ago makes room')
  assert.equal(ofHost('claude.ai').length, 200)
  assert.equal(clients.has(oldest.client_id), false)
  assert.equal(clients.has(hostFull.json().client_id), true)
  pin()
  const pinned = await paced(h, { client_name: 'yet another', redirect_uris: ['https://claude.ai/cb/pinned'] })
  assert.equal(pinned.status, 429, 'consented clients are never evicted')
  assert.equal(pinned.json().error, 'too_many_clients')
  assert.equal(pinned.headers.get('retry-after'), '60')
  assert.equal(ofHost('claude.ai').length, 200)
  for (let index = 0; index < 200; index++) assert.equal((await paced(h, { client_name: `a ${index}`, redirect_uris: [`https://a.test/cb/${index}`] })).status, 201)
  for (let index = 0; clients.size < 500; index++) assert.equal((await paced(h, { client_name: `b ${index}`, redirect_uris: [`https://b.test/cb/${index}`] })).status, 201)
  assert.equal(clients.size, 500)
  const evicted = ofHost('a.test')[0]
  assert.equal((await paced(h, { client_name: 'the 501st', redirect_uris: ['https://b.test/cb/overflow'] })).status, 201, 'the global cap evicts the same way')
  assert.equal(clients.size, 500)
  assert.equal(clients.has(evicted.client_id), false)
  pin()
  assert.equal((await paced(h, { client_name: 'the 502nd', redirect_uris: ['https://b.test/cb/overflow2'] })).status, 429)
  h.clock.advance(31 * 24 * 3_600_000)
  await h.reader.sweep()
  assert.equal(clients.size, 0, 'unused clients expire after thirty days')
  assert.equal((await paced(h, { client_name: 'fresh', redirect_uris: ['https://b.test/cb/fresh'] })).status, 201)
  const consented = await session(h)
  h.clock.advance(61 * 60_000)
  await h.reader.sweep()
  assert.equal(clients.size, 1, 'a client nobody consented to lives an hour')
  assert.equal(clients.get(consented.clientId)?.authorized_at > 0, true)
  const address = { 'x-forwarded-for': '198.51.100.5' }
  for (let index = 0; index < 5; index++) assert.equal((await register(h, { client_name: `burst ${index}`, redirect_uris: [`https://claude.ai/cb/burst${index}`] }, address)).status, 201)
  const burst = await register(h, { client_name: 'burst 5', redirect_uris: ['https://claude.ai/cb/burst5'] }, address)
  assert.equal(burst.status, 429, 'five registrations a minute per address')
  assert.equal(burst.json().error, 'temporarily_unavailable')
  assert.ok(Number(burst.headers.get('retry-after')) >= 1)
  assert.equal((await register(h, { client_name: 'elsewhere', redirect_uris: ['https://claude.ai/cb/elsewhere'] })).status, 201, 'another address is unaffected')
  secretsAbsent(h)
})

test('authorization request: exact redirect, S256 only, exact resource, bounded scope and state, no duplicates, per-address limits', async t => {
  const h = await harness(t)
  const clientId = (await register(h)).json().client_id
  const { challenge } = pkce()
  const page = async (params, code) => {
    const response = await h.request(authorizeURL(h, { clientId, challenge, ...params }).pathname + authorizeURL(h, { clientId, challenge, ...params }).search)
    assert.equal(response.status, 400, JSON.stringify(params))
    assert.match(response.body, new RegExp(`Wappie MCP: ${code}`))
    assert.equal(response.headers.get('content-type'), 'text/html; charset=utf-8')
  }
  const bounced = async (params, code) => {
    const url = authorizeURL(h, { clientId, challenge, ...params })
    const response = await h.request(url.pathname + url.search)
    assert.equal(response.status, 302, JSON.stringify(params))
    const location = new URL(response.location)
    assert.equal(location.origin + location.pathname, REDIRECT_URI)
    assert.equal(location.searchParams.get('error'), code)
    assert.equal(location.searchParams.get('iss'), h.publicOrigin)
    assert.equal(location.searchParams.get('state'), url.searchParams.get('state'))
  }
  await page({ clientId: 'nobody' }, 'invalid_client')
  await page({ clientId: null }, 'invalid_client')
  await page({ redirectUri: REDIRECT_URI + '/' }, 'invalid_redirect_uri')
  await page({ redirectUri: 'https://claude.ai/api/mcp/auth_callback?x=1' }, 'invalid_redirect_uri')
  await page({ redirectUri: null }, 'invalid_redirect_uri')
  await bounced({ code_challenge_method: 'plain' }, 'invalid_request')
  await bounced({ code_challenge_method: null }, 'invalid_request')
  await bounced({ challenge: 'short' }, 'invalid_request')
  await bounced({ challenge: null }, 'invalid_request')
  await bounced({ resource: `${h.publicOrigin}/other` }, 'invalid_target')
  await bounced({ resource: `${h.resource}/` }, 'invalid_target')
  await bounced({ resource: null }, 'invalid_target')
  await bounced({ scope: 'wappie:write' }, 'invalid_scope')
  await bounced({ scope: 'wappie:read offline_access' }, 'invalid_scope')
  await bounced({ scope: '' }, 'invalid_scope')
  await bounced({ state: 'x'.repeat(513) }, 'invalid_request')
  await bounced({ response_type: 'token' }, 'unsupported_response_type')
  const url = authorizeURL(h, { clientId, challenge })
  assert.equal((await h.request(url.pathname + url.search + '&scope=wappie:read')).status, 400, 'a repeated parameter is refused')
  assert.equal((await h.request(url.pathname + url.search, { method: 'POST' })).status, 405)
  assert.equal(h.reader.state.pending.size, 0, 'nothing pending was created by a refused request')
  const noScope = authorizeURL(h, { clientId, challenge, scope: null, state: null })
  const accepted = await h.request(noScope.pathname + noScope.search)
  assert.equal(accepted.status, 302)
  assert.equal(new URL(accepted.location).origin, 'https://console.example.test')
  assert.equal(new URL(accepted.location).pathname, '/console')
  assert.match(new URL(accepted.location).searchParams.get('mcp_connect'), /^[A-Za-z0-9_-]{22}$/)
  const ip = address => ({ headers: { 'x-forwarded-for': address } })
  for (let index = 1; index < 10; index++) assert.equal((await h.request(url.pathname + url.search, ip('203.0.113.7'))).status, 302)
  assert.equal((await h.request(url.pathname + url.search, ip('203.0.113.7'))).status, 302)
  const tooMany = await h.request(url.pathname + url.search, ip('203.0.113.7'))
  assert.equal(tooMany.status, 429, 'ten pending requests per address')
  for (let index = 0; index < 20; index++) await h.request(url.pathname + url.search, ip('203.0.113.8'))
  assert.equal((await h.request(url.pathname + url.search, ip('203.0.113.8'))).status, 429, 'twenty authorizations per address per minute')
  assert.equal((await h.request(url.pathname + url.search, ip('203.0.113.9'))).status, 302, 'another address is unaffected')
  for (let index = 0; index < 10; index++) assert.equal((await h.request(url.pathname + url.search, ip(`2001:db8:2:2::${index + 1}`))).status, 302)
  assert.equal((await h.request(url.pathname + url.search, ip('2001:db8:2:2:ffff::9'))).status, 429, 'the per-address counts see one IPv6 /64 as one address')
  assert.equal((await h.request(url.pathname + url.search, ip('2001:db8:2:3::9'))).status, 302, 'the next /64 is another address')
  // Two hundred requests nobody consented to are the ceiling; beyond it the oldest of them makes room rather than every consent start failing.
  const pending = h.reader.state.pending
  h.clock.advance(10_000)
  const consented = await consent(h, authorizeURL(h, { clientId, challenge }), { until: 'bundle' })
  assert.equal(consented.relayed.status, 204)
  const unconsented = () => [...pending.values()].filter(item => !item.bundle)
  const first = unconsented()[0]
  for (let block = 0; unconsented().length < 200; block++) for (let index = 0; index < 10 && unconsented().length < 200; index++) assert.equal((await h.request(url.pathname + url.search, ip(`10.${block}.0.1`))).status, 302)
  const size = pending.size
  assert.equal((await h.request(url.pathname + url.search, ip('10.255.0.1'))).status, 302)
  assert.equal(pending.size, size)
  assert.equal(unconsented().length, 200)
  assert.equal(pending.has(first.id), false, 'the oldest unconsented request was forgotten')
  assert.equal(pending.get(consented.id)?.bundle !== undefined, true, 'the consented one was not')
  h.clock.advance(21 * 60_000)
  await h.reader.sweep()
  assert.equal(h.reader.state.pending.size, 0)
  secretsAbsent(h, { linkSecrets: [consented.linkSecret] })
})

test('token endpoint: every mismatch is invalid_grant, a replayed code kills its family, resources and grants are checked', async t => {
  const h = await harness(t)
  const { clientId, verifier, done, tokens } = await session(h)
  assert.equal(tokens.token_type, 'Bearer')
  assert.equal(tokens.scope, 'wappie:read')
  assert.ok(tokens.expires_in > 0 && tokens.expires_in <= 900)
  assert.match(tokens.access_token, /^wmcp_a_[A-Za-z0-9_-]{43}$/)
  assert.match(tokens.refresh_token, /^wmcp_r_[A-Za-z0-9_-]{43}$/)
  const code = new URL(done.completed.location).searchParams.get('code')
  assert.match(code, /^wmcp_c_[A-Za-z0-9_-]{43}$/)
  assert.equal((await rpc(h, tokens.access_token)).status, 200)
  const replay = await exchange(h, { code, clientId, verifier })
  assert.equal(replay.status, 400)
  assert.equal(replay.json().error, 'invalid_grant')
  assert.equal((await rpc(h, tokens.access_token)).status, 401, 'the family issued from the replayed code is dead')
  assert.equal(h.go.connections.get(done.connectionId).status, 'revoked', 'and Go was told')
  const fresh = async () => {
    const { challenge, verifier } = pkce()
    const consented = await consent(h, authorizeURL(h, { clientId, challenge }))
    assert.equal(consented.completed.status, 302)
    return { code: new URL(consented.completed.location).searchParams.get('code'), verifier, consented }
  }
  const grant = (code) => exchange(h, { code: code.code, clientId, verifier: code.verifier })
  const invalid = async (code, overrides, error = 'invalid_grant') => {
    const response = await exchange(h, { code: code.code, clientId, verifier: code.verifier, ...overrides })
    assert.equal(response.status, 400, JSON.stringify(overrides))
    assert.equal(response.json().error, error, JSON.stringify(overrides))
  }
  let attempt = await fresh()
  await invalid(attempt, { verifier: pkce().verifier })
  assert.equal((await grant(attempt)).status, 400, 'a failed exchange consumes the code')
  attempt = await fresh()
  await invalid(attempt, { redirectUri: REDIRECT_URI + '/' })
  attempt = await fresh()
  await invalid(attempt, { clientId: (await register(h, { client_name: 'Other' })).json().client_id })
  attempt = await fresh()
  await invalid(attempt, { resource: null }, 'invalid_target')
  await invalid(attempt, { resource: `${h.publicOrigin}/mcp/` }, 'invalid_target')
  await invalid(attempt, { grant_type: 'password' }, 'unsupported_grant_type')
  await invalid(attempt, { clientId: null }, 'invalid_request')
  assert.equal((await h.request('/mcp/token', { method: 'POST', headers: { 'content-type': 'application/x-www-form-urlencoded' }, body: 'grant_type=authorization_code&grant_type=refresh_token&client_id=x' })).json().error, 'invalid_request')
  assert.equal((await h.request('/mcp/token', { method: 'POST', headers: { 'content-type': 'application/json' }, body: '{}' })).json().error, 'invalid_request')
  assert.equal((await h.request('/mcp/token')).status, 405)
  assert.equal((await grant(attempt)).status, 200, 'request-shape errors do not consume the code')
  attempt = await fresh()
  h.clock.advance(61_000)
  await invalid(attempt, {})
  await invalid({ code: `wmcp_c_${'B'.repeat(43)}`, verifier: attempt.verifier }, {})
  await invalid({ code: 'not-a-code', verifier: attempt.verifier }, {})
  // A garbage grant naming a public client_id is charged to the address, never to the client's other users.
  const shared = await session(h)
  const garbage = (address, count) => Promise.all(Array.from({ length: count }, () => h.form('/mcp/token', { grant_type: 'refresh_token', refresh_token: 'x', client_id: shared.clientId }, { 'x-forwarded-for': address })))
  for (const response of await garbage('198.51.100.9', 20)) assert.equal(response.status, 400)
  const unaffected = await refresh(h, { refreshToken: shared.tokens.refresh_token, clientId: shared.clientId })
  assert.equal(unaffected.status, 200, 'a legitimate user of the same client_id is unaffected')
  await garbage('2001:db8:1:2::5', 300)
  // The bucket refills continuously (five a second), so a slow runner may earn
  // a token or two back while the burst is in flight; a short follow-up burst
  // from the same /64 must still hit the ceiling.
  const followUp = await garbage('2001:db8:1:2:ffff::1', 10)
  const limited = followUp.find(response => response.status === 429)
  assert.ok(limited, 'three hundred a minute per address, an IPv6 /64 being one address')
  assert.equal(limited.json().error, 'temporarily_unavailable')
  assert.ok(Number(limited.headers.get('retry-after')) >= 1)
  assert.equal((await garbage('2001:db8:1:3::1', 1))[0].status, 400, 'the next /64 is another address')
  assert.equal((await refresh(h, { refreshToken: unaffected.json().refresh_token, clientId: shared.clientId })).status, 200, 'and the legitimate user still is not')
  secretsAbsent(h, { tokens: [tokens.access_token, tokens.refresh_token, code], linkSecrets: [done.linkSecret] })
})

test('refresh rotation: identical pair inside the grace window, dead family afterwards or for a grandparent, per-client limits, revocation', async t => {
  const h = await harness(t)
  const { clientId, tokens, done } = await session(h)
  const first = await refresh(h, { refreshToken: tokens.refresh_token, clientId })
  assert.equal(first.status, 200)
  const pair = first.json()
  assert.notEqual(pair.refresh_token, tokens.refresh_token)
  assert.equal((await rpc(h, pair.access_token)).status, 200)
  const retried = await refresh(h, { refreshToken: tokens.refresh_token, clientId })
  assert.equal(retried.status, 200)
  assert.deepEqual(retried.json(), pair, 'a retry inside the grace window receives the identical pair')
  h.clock.advance(31_000)
  const late = await refresh(h, { refreshToken: tokens.refresh_token, clientId })
  assert.equal(late.status, 400)
  assert.equal(late.json().error, 'invalid_grant')
  assert.equal((await rpc(h, pair.access_token)).status, 401, 'the family is dead')
  assert.equal((await refresh(h, { refreshToken: pair.refresh_token, clientId })).status, 400)
  assert.equal(h.go.connections.get(done.connectionId).status, 'revoked')

  const parallel = await session(h)
  h.go.delay = 150
  const [a, b] = await Promise.all([refresh(h, { refreshToken: parallel.tokens.refresh_token, clientId: parallel.clientId }), refresh(h, { refreshToken: parallel.tokens.refresh_token, clientId: parallel.clientId })])
  h.go.delay = 0
  assert.equal(a.status, 200); assert.equal(b.status, 200)
  assert.deepEqual(a.json(), b.json(), 'concurrent refreshes of one token receive the same pair')
  assert.equal((await rpc(h, a.json().access_token)).status, 200)
  assert.equal(h.reader.state.tokens.size, 4, 'one rotation happened: the old pair plus its successor')
  assert.equal([...h.reader.state.tokens.values()].some(token => 'successor_pair' in token || JSON.stringify(token).includes(a.json().refresh_token)), false, 'the persisted records never carry the successor pair')
  h.clock.advance(31_000)
  await h.reader.sweep()
  assert.equal((await rpc(h, a.json().access_token)).status, 200, 'the rotated family itself lives on')

  // The successor pair lives only in memory: after a restart a presentation inside the grace window is a replay.
  const restarted = await session(h)
  const rotated = (await refresh(h, { refreshToken: restarted.tokens.refresh_token, clientId: restarted.clientId })).json()
  await h.restart()
  assert.equal((await refresh(h, { refreshToken: restarted.tokens.refresh_token, clientId: restarted.clientId })).json().error, 'invalid_grant')
  assert.equal((await rpc(h, rotated.access_token)).status, 401, 'and the family is dead')
  assert.equal(h.go.connections.get(restarted.done.connectionId).status, 'revoked')

  const lineage = await session(h)
  const second = (await refresh(h, { refreshToken: lineage.tokens.refresh_token, clientId: lineage.clientId })).json()
  const third = (await refresh(h, { refreshToken: second.refresh_token, clientId: lineage.clientId })).json()
  assert.equal((await rpc(h, third.access_token)).status, 200)
  const grandparent = await refresh(h, { refreshToken: lineage.tokens.refresh_token, clientId: lineage.clientId })
  assert.equal(grandparent.json().error, 'invalid_grant')
  assert.equal((await rpc(h, third.access_token)).status, 401, 'a grandparent presentation kills the whole family')

  const wrongClient = await session(h)
  const other = (await register(h, { client_name: 'Other' })).json().client_id
  assert.equal((await refresh(h, { refreshToken: wrongClient.tokens.refresh_token, clientId: other })).json().error, 'invalid_grant')
  assert.equal((await rpc(h, wrongClient.tokens.access_token)).status, 401)

  const target = await session(h)
  assert.equal((await refresh(h, { refreshToken: target.tokens.refresh_token, clientId: target.clientId, resource: `${h.publicOrigin}/x` })).json().error, 'invalid_target')
  assert.equal((await refresh(h, { refreshToken: target.tokens.refresh_token, clientId: target.clientId, resource: null })).status, 200, 'resource is optional on refresh')
  assert.equal((await refresh(h, { refreshToken: `wmcp_r_${'C'.repeat(43)}`, clientId: target.clientId })).json().error, 'invalid_grant')

  const goRevoked = await session(h)
  h.go.connections.get(goRevoked.done.connectionId).status = 'revoked'
  assert.equal((await refresh(h, { refreshToken: goRevoked.tokens.refresh_token, clientId: goRevoked.clientId })).json().error, 'invalid_grant', 'refresh re-checks Go')
  assert.equal(h.reader.state.connections.has(goRevoked.done.connectionId), false)

  const idle = await session(h)
  h.clock.advance(31 * 24 * 3_600_000)
  assert.equal((await refresh(h, { refreshToken: idle.tokens.refresh_token, clientId: idle.clientId })).json().error, 'invalid_grant', 'an idle refresh token expires')

  const family = await session(h)
  let current = family.tokens.refresh_token
  for (let index = 0; index < 20; index++) {
    const response = await refresh(h, { refreshToken: current, clientId: family.clientId })
    assert.equal(response.status, 200)
    current = response.json().refresh_token
  }
  const perFamily = await refresh(h, { refreshToken: current, clientId: family.clientId })
  assert.equal(perFamily.status, 429, 'twenty refreshes per family per minute')
  assert.equal((await refresh(h, { refreshToken: idle.tokens.refresh_token, clientId: family.clientId })).status, 400, 'another family under the same address is not limited')
  h.clock.advance(60_000)
  assert.equal((await refresh(h, { refreshToken: current, clientId: family.clientId })).status, 200)

  const revoked = await session(h)
  assert.equal((await h.form('/mcp/revoke', { token: revoked.tokens.refresh_token, client_id: revoked.clientId })).status, 200)
  assert.equal((await rpc(h, revoked.tokens.access_token)).status, 401)
  assert.equal(h.go.connections.get(revoked.done.connectionId).status, 'revoked')
  assert.equal((await h.form('/mcp/revoke', { token: 'unknown' })).status, 200, 'RFC 7009 always answers 200')
  assert.equal((await h.request('/mcp/revoke')).status, 405)
  const byAccess = await session(h)
  assert.equal((await h.form('/mcp/revoke', { token: byAccess.tokens.access_token })).status, 200)
  assert.equal((await refresh(h, { refreshToken: byAccess.tokens.refresh_token, clientId: byAccess.clientId })).status, 400)
  secretsAbsent(h, { tokens: [tokens.access_token, tokens.refresh_token, pair.access_token, pair.refresh_token, third.access_token], linkSecrets: [done.linkSecret] })
})

test('consent completion: only the console origin may post, bad proofs burn after three tries, consumed requests never replay', async t => {
  const h = await harness(t)
  const provider = clientProvider()
  assert.equal(await auth(provider, { serverUrl: h.resource }), 'REDIRECT')
  const evil = await consent(h, provider.store.authorizationUrl, { origin: 'https://evil.example' })
  assert.equal(evil.completed.status, 400)
  assert.match(evil.completed.body, /invalid_origin/)
  assert.equal(h.go.activations, 0, 'no state change')
  const missing = await h.form('/mcp/authorize/complete', { request: evil.id, proof: evil.proof })
  assert.equal(missing.status, 400)
  const good = await h.form('/mcp/authorize/complete', { request: evil.id, proof: evil.proof }, { origin: h.consoleOrigin })
  assert.equal(good.status, 302, 'the same request completes once the console posts it')
  assert.equal(h.go.activations, 1)
  const replay = await h.form('/mcp/authorize/complete', { request: evil.id, proof: evil.proof }, { origin: h.consoleOrigin })
  assert.equal(replay.status, 400)
  assert.match(replay.body, /invalid_proof/)
  assert.equal((await h.form('/mcp/authorize/complete', { request: 'AAAAAAAAAAAAAAAAAAAAAA', proof: evil.proof }, { origin: h.consoleOrigin })).status, 400)
  assert.equal((await h.form('/mcp/authorize/complete', { request: 'short', proof: evil.proof }, { origin: h.consoleOrigin })).status, 400)
  assert.equal((await h.request('/mcp/authorize/complete', { method: 'POST', headers: { origin: h.consoleOrigin, 'content-type': 'application/json' }, body: '{}' })).status, 400)
  assert.equal((await h.request('/mcp/authorize/complete', { headers: { origin: h.consoleOrigin } })).status, 405)
  const second = clientProvider()
  assert.equal(await auth(second, { serverUrl: h.resource }), 'REDIRECT')
  const tampered = await consent(h, second.store.authorizationUrl, { proof: `${'A'.repeat(43)}` })
  assert.equal(tampered.completed.status, 400)
  assert.equal(h.go.connections.get(tampered.connectionId).status, 'pending')
  const wrongLength = await h.form('/mcp/authorize/complete', { request: tampered.id, proof: 'AAAA' }, { origin: h.consoleOrigin })
  assert.equal(wrongLength.status, 400)
  const flipped = tampered.proof.slice(0, 10) + (tampered.proof[10] === 'A' ? 'B' : 'A') + tampered.proof.slice(11)
  const third = await h.form('/mcp/authorize/complete', { request: tampered.id, proof: flipped }, { origin: h.consoleOrigin })
  assert.equal(third.status, 400)
  await new Promise(resolve => setTimeout(resolve, 50))
  assert.equal(h.go.connections.get(tampered.connectionId).status, 'revoked', 'three failures burn the request and revoke the connection')
  assert.equal((await h.form('/mcp/authorize/complete', { request: tampered.id, proof: tampered.proof }, { origin: h.consoleOrigin })).status, 400, 'the right proof is too late')
  assert.equal((await h.internal(`/internal/requests/${tampered.id}`)).status, 404)
  for (let index = 0; index < 10; index++) await h.form('/mcp/authorize/complete', { request: 'AAAAAAAAAAAAAAAAAAAAAA', proof: 'x' }, { origin: h.consoleOrigin, 'x-forwarded-for': '198.51.100.4' })
  const limited = await h.form('/mcp/authorize/complete', { request: 'AAAAAAAAAAAAAAAAAAAAAA', proof: 'x' }, { origin: h.consoleOrigin, 'x-forwarded-for': '198.51.100.4' })
  assert.equal(limited.status, 429)
  assert.equal(h.logs.some(line => JSON.parse(line).code === 'proof_burned'), true)
  const failedActivation = clientProvider()
  assert.equal(await auth(failedActivation, { serverUrl: h.resource }), 'REDIRECT')
  const stale = await consent(h, failedActivation.store.authorizationUrl, { until: 'bundle' })
  h.go.connections.get(stale.connectionId).status = 'revoked'
  const proof = (await import('./harness.mjs')).proof(stale.linkSecret, { requestID: stale.id, clientID: stale.descriptor.client_id, codeChallenge: stale.descriptor.code_challenge, sealedBytes: stale.sealedBytes })
  const notActivated = await h.form('/mcp/authorize/complete', { request: stale.id, proof }, { origin: h.consoleOrigin })
  assert.equal(notActivated.status, 502)
  assert.match(notActivated.body, /activation_failed/)
  assert.equal(h.reader.state.connections.has(stale.connectionId), false)
  secretsAbsent(h, { linkSecrets: [evil.linkSecret, tampered.linkSecret, stale.linkSecret], proofs: [evil.proof, tampered.proof, proof] })
})

test('the SDK client recovers from invalid_grant by re-authorizing, and a second consent yields a second connection', async t => {
  const h = await harness(t)
  const { provider, done } = await authorize(h, { auth })
  h.go.connections.get(done.connectionId).status = 'revoked'
  h.clock.advance(61_000)
  assert.equal((await rpc(h, provider.store.tokens.access_token)).status, 401)
  // The SDK tries the refresh token first, is told invalid_grant, and asks for a new authorization.
  assert.equal(await auth(provider, { serverUrl: h.resource }), 'REDIRECT')
  const again = await consent(h, provider.store.authorizationUrl)
  assert.equal(again.completed.status, 302)
  assert.notEqual(again.connectionId, done.connectionId)
  const back = new URL(again.completed.location)
  assert.equal(await auth(provider, { serverUrl: h.resource, authorizationCode: back.searchParams.get('code'), iss: back.searchParams.get('iss') }), 'AUTHORIZED')
  assert.equal((await rpc(h, provider.store.tokens.access_token)).status, 200)
  assert.equal(h.reader.state.connections.size, 1)
  secretsAbsent(h, { linkSecrets: [done.linkSecret, again.linkSecret] })
})
