package wa

import (
	"context"
	"fmt"
	"time"

	"go.mau.fi/whatsmeow/types"
)

// ReceiptMode decides what a device tells the other side.
type ReceiptMode string

const (
	// ModePassive is the default and is what "incognito" means here.
	//
	// Presence is never announced, so whatsmeow's internal sendActiveReceipts
	// counter stays at zero and delivery receipts leave typed "inactive".
	// Official clients receive those and do not render them, which is exactly
	// what WhatsApp Web does when it is not in the foreground. Read and played
	// receipts are only ever sent when something explicitly asks.
	ModePassive ReceiptMode = "passive"

	// ModeActive behaves like a normal client: presence is announced on
	// connect, and delivery receipts render as the usual grey ticks.
	ModeActive ReceiptMode = "active"
)

// ParseReceiptMode validates a mode coming from configuration or the database.
func ParseReceiptMode(s string) (ReceiptMode, error) {
	switch ReceiptMode(s) {
	case ModePassive:
		return ModePassive, nil
	case ModeActive:
		return ModeActive, nil
	default:
		return "", fmt.Errorf("wa: unknown receipt mode %q, want %q or %q", s, ModePassive, ModeActive)
	}
}

// ReceiptPolicy is the single place that decides whether a receipt leaves.
//
// Everything about incognito funnels through here, for two reasons. It keeps
// the decision auditable — one type to read, one set of tests to trust — and it
// gives the eventual whatsmeow fork exactly one seam to slot into. The v1
// server had no such place: SendPresence(available) was called inline in the
// Connected handler with a comment explaining that it made delivery receipts
// render, and that single line silently defeated any attempt at going quiet.
type ReceiptPolicy struct {
	Mode ReceiptMode

	// Recorder observes each decision. Wired to the metrics counter in
	// production, and to an assertion in tests.
	Recorder func(kind, decision string)
}

// Receipt kinds, used as metric label values.
const (
	KindPresence = "presence"
	KindRead     = "read"
	KindPlayed   = "played"
	KindTyping   = "typing"
)

// Decision outcomes.
const (
	decisionSent       = "sent"
	decisionSuppressed = "suppressed"
)

func (p ReceiptPolicy) record(kind string, sent bool) {
	if p.Recorder == nil {
		return
	}
	if sent {
		p.Recorder(kind, decisionSent)
		return
	}
	p.Recorder(kind, decisionSuppressed)
}

// OnConnect applies the policy right after a connection is established.
//
// In passive mode this does nothing at all, and the nothing is the feature:
// not calling SendPresence is what keeps whatsmeow emitting "inactive" delivery
// receipts. There is no upstream flag to suppress delivery receipts outright —
// sendMessageReceipt is called unconditionally on the inbound path — so silence
// here is the entire mechanism.
func (p ReceiptPolicy) OnConnect(ctx context.Context, c Client) error {
	if p.Mode != ModeActive {
		p.record(KindPresence, false)
		return nil
	}
	p.record(KindPresence, true)
	if err := c.SendPresence(ctx, types.PresenceAvailable); err != nil {
		return fmt.Errorf("wa: announce presence: %w", err)
	}
	return nil
}

// OnDisconnect returns to invisibility. Sending "unavailable" resets
// whatsmeow's active-receipt counter from 1 back to 0.
//
// Note the asymmetry upstream: SetForceActiveDeliveryReceipts(true) stores 2,
// and presence "unavailable" only moves 1 to 0. So if anything ever forces
// active receipts, this alone will not undo it — clearing that requires an
// explicit SetForceActiveDeliveryReceipts(false), which is why this server
// never calls the setter with true at all.
//
// Returns an error rather than swallowing one: this runs during teardown, where
// a failure is expected and usually uninteresting, but the caller is the one
// positioned to decide whether it is worth a log line.
func (p ReceiptPolicy) OnDisconnect(ctx context.Context, c Client) error {
	if p.Mode != ModeActive {
		return nil
	}
	if err := c.SendPresence(ctx, types.PresenceUnavailable); err != nil {
		return fmt.Errorf("wa: withdraw presence: %w", err)
	}
	return nil
}

// MarkRead sends a read receipt.
//
// Refused outright in passive mode, and that is a change worth naming. It used
// to send in either mode on the grounds that it was always an explicit request
// — nothing in the ingest path called it, so asking for one was a deliberate
// act. That stopped being true when the browser began marking messages read as
// they appear on screen: the request is now generated by looking at a
// conversation, and a posture that promises silence cannot have reading count
// as asking.
func (p ReceiptPolicy) MarkRead(ctx context.Context, c Client, chat, sender types.JID,
	ids []types.MessageID, played bool) error {
	if len(ids) == 0 {
		return nil
	}
	kind := KindRead
	var extra []types.ReceiptType
	if played {
		kind = KindPlayed
		extra = append(extra, types.ReceiptTypePlayed)
	}
	if p.Mode != ModeActive {
		p.record(kind, false)
		return nil
	}
	p.record(kind, true)
	if err := c.MarkRead(ctx, ids, time.Now(), chat, sender, extra...); err != nil {
		return fmt.Errorf("wa: mark read: %w", err)
	}
	return nil
}

// ChatPresence tells a conversation that we are typing, or have stopped.
//
// Gated like every other outbound signal, and for the sharper reason: this one
// reports what a person is doing at this exact moment, in a chat they have open,
// several times a minute. It is the most continuous thing this account can emit.
//
// Suppressed in passive mode by not calling upstream at all. There is no flag
// to ask whatsmeow for silence — silence is what happens when nothing is sent —
// which is the same mechanism the whole incognito posture rests on, and the
// reason fakewa counts these calls.
func (p ReceiptPolicy) ChatPresence(ctx context.Context, c Client, chat types.JID,
	state types.ChatPresence, media types.ChatPresenceMedia) error {
	if p.Mode != ModeActive {
		p.record(KindTyping, false)
		return nil
	}
	p.record(KindTyping, true)
	if err := c.SendChatPresence(ctx, chat, state, media); err != nil {
		return fmt.Errorf("wa: chat presence: %w", err)
	}
	return nil
}
