package wa

import (
	"context"
	"fmt"
	"time"

	"go.mau.fi/whatsmeow/types"
)

// ReceiptMode controls explicit reading and typing signals, not public online
// presence. Every connection stays unavailable in either mode.
type ReceiptMode string

const (
	// ModePassive is the default: suppress explicit read, played and typing
	// signals. Ingestion and protocol acknowledgments continue normally.
	ModePassive ReceiptMode = "passive"

	// ModeActive permits explicit read, played and typing signals while keeping
	// the connection's public presence unavailable.
	ModeActive ReceiptMode = "active"
)

// ParseReceiptMode validates a mode coming from configuration or the database.
func ParseReceiptMode(s string) (ReceiptMode, error) {
	switch ReceiptMode(s) {
	case ModePassive:
		return ModePassive, nil
	case ModeActive:
		return ModeActive, nil
	default:
		return "", fmt.Errorf("wa: unknown receipt mode %q, want %q or %q", s, ModePassive, ModeActive)
	}
}

// ReceiptPolicy is the single place that decides whether a receipt leaves.
//
// Everything about incognito funnels through here, for two reasons. It keeps
// the decision auditable — one type to read, one set of tests to trust — and it
// gives the eventual whatsmeow fork exactly one seam to slot into. The v1
// server had no such place: SendPresence(available) was called inline in the
// Connected handler with a comment explaining that it made delivery receipts
// render, and that single line silently defeated any attempt at going quiet.
type ReceiptPolicy struct {
	Mode ReceiptMode

	// Recorder observes each decision. Wired to the metrics counter in
	// production, and to an assertion in tests.
	Recorder func(kind, decision string)
}

// Receipt kinds, used as metric label values.
const (
	KindPresence = "presence"
	KindRead     = "read"
	KindPlayed   = "played"
	KindTyping   = "typing"
)

// Decision outcomes.
const (
	decisionSent       = "sent"
	decisionSuppressed = "suppressed"
)

func (p ReceiptPolicy) record(kind string, sent bool) {
	if p.Recorder == nil {
		return
	}
	if sent {
		p.Recorder(kind, decisionSent)
		return
	}
	p.Recorder(kind, decisionSuppressed)
}

// OnConnect explicitly withdraws public presence in both reading modes. An
// always-connected linked client must not claim that a person is online merely
// because the server is ingesting messages: that can suppress phone push alerts.
// Protocol acknowledgments remain enabled, using upstream's inactive receipts.
func (p ReceiptPolicy) OnConnect(ctx context.Context, c Client) error {
	return p.withdrawPresence(ctx, c)
}

// OnDisconnect withdraws presence regardless of the current reading mode. The
// caller bounds teardown and decides how to report an already-closed socket.
func (p ReceiptPolicy) OnDisconnect(ctx context.Context, c Client) error {
	return p.withdrawPresence(ctx, c)
}

func (p ReceiptPolicy) withdrawPresence(ctx context.Context, c Client) error {
	// Unavailable only changes upstream's active counter from 1 to 0; a
	// previously forced value of 2 needs this explicit reset first. Reset even
	// if SendPresence cannot run yet because the push name is still syncing.
	c.SetForceActiveDeliveryReceipts(false)
	p.record(KindPresence, true)
	if err := c.SendPresence(ctx, types.PresenceUnavailable); err != nil {
		return fmt.Errorf("wa: withdraw presence: %w", err)
	}
	return nil
}

// MarkRead sends a read receipt.
//
// Refused outright in passive mode, and that is a change worth naming. It used
// to send in either mode on the grounds that it was always an explicit request
// — nothing in the ingest path called it, so asking for one was a deliberate
// act. That stopped being true when the browser began marking messages read as
// they appear on screen: the request is now generated by looking at a
// conversation, and a posture that promises silence cannot have reading count
// as asking.
func (p ReceiptPolicy) MarkRead(ctx context.Context, c Client, chat, sender types.JID,
	ids []types.MessageID, played bool) error {
	if len(ids) == 0 {
		return nil
	}
	kind := KindRead
	var extra []types.ReceiptType
	if played {
		kind = KindPlayed
		extra = append(extra, types.ReceiptTypePlayed)
	}
	if p.Mode != ModeActive {
		p.record(kind, false)
		return nil
	}
	p.record(kind, true)
	if err := c.MarkRead(ctx, ids, time.Now(), chat, sender, extra...); err != nil {
		return fmt.Errorf("wa: mark read: %w", err)
	}
	return nil
}

// ChatPresence tells a conversation that we are typing, or have stopped.
//
// Gated like every other outbound signal, and for the sharper reason: this one
// reports what a person is doing at this exact moment, in a chat they have open,
// several times a minute. It is the most continuous thing this account can emit.
//
// Suppressed in passive mode by not calling upstream at all. There is no flag
// to ask whatsmeow for silence — silence is what happens when nothing is sent —
// which is the same mechanism the whole incognito posture rests on, and the
// reason fakewa counts these calls.
func (p ReceiptPolicy) ChatPresence(ctx context.Context, c Client, chat types.JID,
	state types.ChatPresence, media types.ChatPresenceMedia) error {
	if p.Mode != ModeActive {
		p.record(KindTyping, false)
		return nil
	}
	p.record(KindTyping, true)
	if err := c.SendChatPresence(ctx, chat, state, media); err != nil {
		return fmt.Errorf("wa: chat presence: %w", err)
	}
	return nil
}
