// Generates the A0 probe corpus INSIDE the enclave, from nothing (§4): a
// 12-megapixel JPEG and a 50-page text PDF. No external files. Runs unjailed as
// the runner; the jailed workers then read what it wrote from /opt (bound
// read-only into the jail).
//
//   node gen-corpus.mjs <out-dir>
//
// Writes <out-dir>/image.jpg and <out-dir>/doc.pdf and prints a JSON summary.
import { mkdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import sharp from 'sharp'

const outDir = process.argv[2] || '/opt/probe/corpus'
mkdirSync(outDir, { recursive: true })

// --- 12 MP JPEG (4000x3000), Gaussian noise so it is realistic to decode and
//     encode, not a trivially-compressible solid colour. Generated by libvips,
//     so no large JS buffer is held. ---
const width = 4000
const height = 3000
const imagePath = join(outDir, 'image.jpg')
await sharp({
  create: { width, height, channels: 3, noise: { type: 'gaussian', mean: 128, sigma: 28 } },
})
  .jpeg({ quality: 90 })
  .toFile(imagePath)

// --- 50-page text PDF, written by hand (no PDF library, so the probe image
//     needs no extra dependency). Standard Helvetica and text-showing
//     operators, so pdfjs-dist extracts the text on the jailed side. ---
function buildPdf(pageCount) {
  const enc = new TextEncoder()
  const chunks = []
  let length = 0
  const offsets = []
  const push = (s) => {
    const b = enc.encode(s)
    chunks.push(b)
    length += b.length
  }
  // Object N is written with startObj(N) recording its byte offset.
  const startObj = (n) => {
    offsets[n] = length
    push(`${n} 0 obj\n`)
  }

  push('%PDF-1.4\n%\xE2\xE3\xCF\xD3\n')

  const catalog = 1
  const pagesObj = 2
  const font = 3
  const firstPage = 4 // page i: obj (4 + 2i), content (5 + 2i)

  const kids = []
  for (let i = 0; i < pageCount; i++) kids.push(`${firstPage + 2 * i} 0 R`)

  startObj(catalog)
  push('<< /Type /Catalog /Pages 2 0 R >>\nendobj\n')

  startObj(pagesObj)
  push(`<< /Type /Pages /Kids [${kids.join(' ')}] /Count ${pageCount} >>\nendobj\n`)

  startObj(font)
  push('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n')

  for (let i = 0; i < pageCount; i++) {
    const pageNo = firstPage + 2 * i
    const contentNo = pageNo + 1
    startObj(pageNo)
    push(
      `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] ` +
        `/Resources << /Font << /F1 3 0 R >> >> /Contents ${contentNo} 0 R >>\nendobj\n`,
    )
    const line1 = `Probe page ${i + 1} of ${pageCount}`
    const line2 = 'The quick brown fox jumps over the lazy dog 0123456789'
    const stream =
      `BT /F1 24 Tf 72 720 Td (${line1}) Tj ET\n` +
      `BT /F1 14 Tf 72 680 Td (${line2}) Tj ET\n`
    startObj(contentNo)
    push(`<< /Length ${enc.encode(stream).length} >>\nstream\n${stream}endstream\nendobj\n`)
  }

  const xrefStart = length
  const objCount = firstPage + 2 * pageCount // one past the last object number
  push(`xref\n0 ${objCount}\n`)
  push('0000000000 65535 f \n')
  for (let n = 1; n < objCount; n++) {
    const off = offsets[n] ?? 0
    push(`${String(off).padStart(10, '0')} 00000 n \n`)
  }
  push(`trailer\n<< /Size ${objCount} /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF\n`)

  const out = new Uint8Array(length)
  let at = 0
  for (const b of chunks) {
    out.set(b, at)
    at += b.length
  }
  return out
}

const pdfPath = join(outDir, 'doc.pdf')
const pdf = buildPdf(50)
writeFileSync(pdfPath, pdf)

process.stdout.write(
  JSON.stringify({
    ok: true,
    node: process.versions.node,
    image: { path: imagePath, width, height },
    pdf: { path: pdfPath, pages: 50, bytes: pdf.length },
  }),
)
