package seal_test

import (
	"encoding/base64"
	"encoding/json"
	"os"
	"testing"

	"github.com/google/uuid"

	"whatserver2/internal/crypto/seal"
)

// The other direction.
//
// testdata/vectors.json pins the browser against Go: Go seals, TypeScript
// opens. This pins Go against the browser, because pairing moved into it — the
// device archive key is generated in a tab and sealed there to each account
// that should be able to read that WhatsApp number, and the private half never
// crosses the wire.
//
// That makes a browser-sealed grant a value nothing on this side ever produced,
// and being wrong about it is invisible: the row stores, pairing reports
// success, and the archive that device fills is unreadable by anybody. The
// device key existed for a few milliseconds in a tab that has since closed.
//
// The vector is generated by web/test/grant.spec.ts and committed, so this test
// needs no JavaScript toolchain. Regenerate with: cd web && npm test

type browserGrant struct {
	Tenant            string `json:"tenant"`
	Device            string `json:"device"`
	User              string `json:"user"`
	Epoch             uint16 `json:"epoch"`
	AccountPrivateKey string `json:"account_private_key"`
	AccountPublicKey  string `json:"account_public_key"`
	DeviceKey         string `json:"device_key"`
	GrantRow          string `json:"grant_row"`
	Sealed            string `json:"sealed"`
}

func loadBrowserGrant(t *testing.T) browserGrant {
	t.Helper()
	raw, err := os.ReadFile("../../../web/testdata/browser-grant.json")
	if err != nil {
		t.Fatalf("reading the browser vector: %v\n"+
			"It is generated by the web test suite: cd web && npm test", err)
	}
	var g browserGrant
	if err := json.Unmarshal(raw, &g); err != nil {
		t.Fatal(err)
	}
	return g
}

func TestABrowserSealedGrantOpensInGo(t *testing.T) {
	g := loadBrowserGrant(t)
	tenant := uuid.MustParse(g.Tenant)
	device := uuid.MustParse(g.Device)
	user := uuid.MustParse(g.User)

	// The row is derived here rather than read from the vector, so the two
	// implementations have to agree about the derivation and not merely about
	// the ciphertext.
	row := seal.GrantRow(tenant, device, user, g.Epoch)
	if row.String() != g.GrantRow {
		t.Fatalf("grant row = %s, browser derived %s", row, g.GrantRow)
	}

	priv, err := seal.ParsePrivateKey(unb64(t, g.AccountPrivateKey))
	if err != nil {
		t.Fatal(err)
	}
	opened, err := seal.OpenDirect(priv, seal.KindDeviceGrant, tenant, row, unb64(t, g.Sealed))
	if err != nil {
		t.Fatalf("opening a grant the browser sealed: %v", err)
	}
	if got := base64.StdEncoding.EncodeToString(opened); got != g.DeviceKey {
		t.Errorf("device key = %s, want %s", got, g.DeviceKey)
	}
	if len(opened) != 32 {
		t.Errorf("device key is %d bytes, want 32", len(opened))
	}
}

func TestABrowserSealedGrantIsBoundToItsRow(t *testing.T) {
	g := loadBrowserGrant(t)
	tenant := uuid.MustParse(g.Tenant)
	user := uuid.MustParse(g.User)

	priv, err := seal.ParsePrivateKey(unb64(t, g.AccountPrivateKey))
	if err != nil {
		t.Fatal(err)
	}

	// Same key, same tenant, same account — another device. If this opened,
	// one operator's grant would unlock another operator's WhatsApp number,
	// which is the whole reason the archive key is per device.
	elsewhere := seal.GrantRow(tenant, uuid.MustParse("00000000-0000-4000-8000-0000000000bb"), user, g.Epoch)
	if _, err := seal.OpenDirect(priv, seal.KindDeviceGrant, tenant, elsewhere, unb64(t, g.Sealed)); err == nil {
		t.Error("a grant opened under a device it was not sealed for")
	}
}

func TestABrowserSealedGrantIsBoundToItsKind(t *testing.T) {
	g := loadBrowserGrant(t)
	tenant := uuid.MustParse(g.Tenant)
	device := uuid.MustParse(g.Device)
	user := uuid.MustParse(g.User)

	priv, err := seal.ParsePrivateKey(unb64(t, g.AccountPrivateKey))
	if err != nil {
		t.Fatal(err)
	}
	row := seal.GrantRow(tenant, device, user, g.Epoch)

	// Presented as a content key rather than as a grant. The kind is in both
	// the AAD and the HPKE info, so this fails twice over — which is the point
	// of putting it in both.
	if _, err := seal.OpenDirect(priv, seal.KindContentKey, tenant, row, unb64(t, g.Sealed)); err == nil {
		t.Error("a grant opened as a content key")
	}
}
